"""refactor_some_column_tables

Revision ID: 003
Revises: 002
Create Date: 2026-03-03 03:14:45.115439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('meal_plan_items_recipe_id_fkey'), 'meal_plan_items', type_='foreignkey')
    op.create_foreign_key(None, 'meal_plan_items', 'recipes', ['recipe_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.drop_constraint(op.f('meal_plans_user_id_fkey'), 'meal_plans', type_='foreignkey')
    op.create_foreign_key(None, 'meal_plans', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recipes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recipes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
    op.drop_constraint(op.f('recipes_user_id_fkey'), 'recipes', type_='foreignkey')
    op.create_foreign_key(None, 'recipes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_foreign_key(op.f('recipes_user_id_fkey'), 'recipes', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.alter_column('recipes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recipes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'meal_plans', type_='foreignkey')
    op.create_foreign_key(op.f('meal_plans_user_id_fkey'), 'meal_plans', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_constraint(None, 'meal_plan_items', type_='foreignkey')
    op.create_foreign_key(op.f('meal_plan_items_recipe_id_fkey'), 'meal_plan_items', 'recipes', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
